### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dfeeley** [JohnStrunk/events2dolphin#2]
Hi John, sorry to bother you, but I wonder could you please publish an .exe release with the encoding change?  I don't have a development env on the only windows computer i have access to (swim club laptop), so instead I need to copy across scb files to a linux machine, run python events2dolphin there, and then copy back the dolphin events csv to windows.  Would be nice to have an updated .exe instead.
thanks again for this utility.
Dave

**Comment by JohnStrunk** [comment]
Here you go: https://github.com/JohnStrunk/events2dolphin/releases/tag/v0.5.1

Glad you find it useful.

**Comment by dfeeley** [comment]
thanks!
