### ISSUE TITLE
32 bit

### ISSUE THREAD

**Issue by agable12** [JohnStrunk/events2dolphin#3]
Thanks so much for creating this.  I am having an issue running the .exe on this old windows 7 laptop the swim team uses.   I am assuming the .exe is compiled for 64 bit.  Any chance we could get a 32 bit version.

**Comment by JohnStrunk** [comment]
A quick search says this should be possible, but it may take me a little while.

**Comment by agable12** [comment]
Ok, I can work around it, should probably get the team a new laptop
anyway😂.  Thanks so much for the utility, upgrading the software would  be
pointless without it.

**Comment by JohnStrunk** [comment]
Give the attached file a try. I don't have a Win7 or 32-bit machine to test on, but it does seem to run on my Win10-x64 😁 
[events2dolphin-x86.exe.zip](https://github.com/JohnStrunk/events2dolphin/files/8838397/events2dolphin-x86.exe.zip)

If it works, I'll make an actual release for it.

**Comment by agable12** [comment]
Thanks, works great!  You are the best!

**Comment by JohnStrunk** [comment]
Thanks for you help @agable12!
I've published a new release w/ both versions. Closing this issue. Feel free to re-open if there's a problem.
